### ISSUE TITLE
dvbtune not switching frequence (Sundtek DVB-C)

### ISSUE THREAD

**Issue by assachs** [sp4rkie/docsis-cable-load-monitor#4] opened 2020-10-07 18:26 UTC
Hello sparkie,

i cannot record the data, because dvbtune is hanging.

E.g.:
dvbtune -c 0 -f 698000000 -s 6952 -qam 64
Using DVB card "Sundtek DVB-C (III)"
tuning DVB-C to 698000000, srate=6952000
polling....
polling....
polling....

I can switch the frequence with mediaclient:

/opt/bin/mediaclient -d /dev/dvb/adapter0/frontend0 -m DVBC -f 698000000 -M Q64 -S 6952000
Using device: /dev/dvb/adapter0/frontend0
Checking for lock:
. [LOCKED]

Do you have an idea, what could be the reason?

Thanks
Andi

**Comment by sp4rkie** [comment] 2020-10-08 06:11
when using standard 'dvd-tools'  manually you must prepend the 'libmediaclient' library to your calls (with means of 'LD_PRELOAD='). That is what 'CableLoadMonitor' does. Otherwise it won't work for Sundtek cards. 

When using Sundtek-proprietary 'mediaclient' this is not required because it automatically uses the 'libmediaclient' library.
e.g.

        LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 626000000 -s 6952 -qam 256

should work for you. For further reference just have a look into 'CableLoadMonitor.log'. All the CLI commands  recorded there are directly suitable for manual cutting&pasting

**Comment by assachs** [comment] 2020-10-08 06:31
Sorry i already tried the command from CableLoadMonitor.log, but did not mention this.

I got the following error

`./CableLoadMonitor

evaluating given downstream channel frequencies

downstream channel frequencies now in use: [ 32 ]

138/QAM256 114/QAM256 130/QAM256 146/QAM256 602/QAM256 618/QAM256 626/QAM256

642/QAM256 650/QAM256 658/QAM256 666/QAM256 674/QAM256 682/QAM256 690/QAM256

698/QAM64  706/QAM64  714/QAM64  722/QAM64  730/QAM64  738/QAM64  746/QAM64

754/QAM64  762/QAM64  770/QAM64  778/QAM64  786/QAM64  794/QAM64  802/QAM64

810/QAM64  818/QAM64  826/QAM64  834/QAM64

graph display mode: standard

graph destination dir: /home/pi/cableload/

recording RRA step size: 10 seconds

recording RRA history size: 7 day(s) 0 hour(s) 0 minute(s) 0 second(s)

using multiple DVB-C tuners: in parallel (if applicable)

DVB-C failure recovery method: retry

generating graph for:   1h recording length, size 1400x1000 pixels

generating graph for:   6h recording length, size 1400x1000 pixels

generating graph for:   1d recording length, size 1400x1000 pixels

generating graph for:   7d recording length, size 1400x1000 pixels

DVB-C tuner(s) found: 1, using thereof: 1

07:22:10:
dvbtune/dvbsnoop fails for [ 138 ] [ 7 != 3 ], retrying...

CMD: sudo systemctl stop sundtek; sleep 5; sudo systemctl start sundtek; sleep 15`

I debuged the follwoing commands:
`{ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 138000000 -s 6952 -qam 256; LD_PRELOAD=/opt/lib/libmediaclient.so timeout 1 dvbsnoop -adapter 0 -s bandwidth 8190 -n 80000; } 2>&1
## PID: 8190 (0x1ffe)   bad/total packets: 0/0 (= nan%)   Avrg:     0.000 kbit/s
dvbtune/dvbsnoop fails for [ 138 ] [ 7 != 3 ], retrying...`

dvbtune is timing out, and the frequence is not changed.

**Comment by sp4rkie** [comment] 2020-10-08 06:38
could you please retry and post the log with 'verbose option' active. e.g.

        CableLoadMonitor -v

**Comment by assachs** [comment] 2020-10-08 07:22
[CableLoadMonitor.log](https://github.com/sp4rkie/docsis-cable-load-monitor/files/5345988/CableLoadMonitor.log)

**Comment by sp4rkie** [comment] 2020-10-08 07:46
you did change the script. It now uses 'mediaclient' but not 'dvbtune'. That's why parsing the output can no longer work. Please use the original script and post with '-v' option should there still remain problems.

**Comment by sp4rkie** [comment] 2020-10-08 07:54
the tuner does not get any signal for some reason. Normally it looks like this:
        
        tuning DVB-C to 634000000, srate=6952000
        polling....
        Getting frontend event
        FE_STATUS:
        polling....
        Getting frontend event
        FE_STATUS: FE_HAS_SIGNAL FE_HAS_LOCK FE_HAS_CARRIER FE_HAS_VITERBI FE_HAS_SYNC
        Bit error rate: 0
        Signal strength: 0
        SNR: 0
        FE_STATUS: FE_HAS_SIGNAL FE_HAS_LOCK FE_HAS_CARRIER FE_HAS_VITERBI FE_HAS_SYNC

i.e. it must get 'FE_STATUS'

138 MHz (as denoted in your log file) appears to be very  low. Is that correct? In your example above you use 698 MHz

you say

        /opt/bin/mediaclient -d /dev/dvb/adapter0/frontend0 -m DVBC -f 698000000 -M Q64 -S 6952000

works. What does

        LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
        
do?

**Comment by assachs** [comment] 2020-10-08 08:24
dvbtune is always "polling". Independently of the frequence. I can't see FE_STATUS. The frequence is not changing.

dvbsnoop get the data from the last frequence.  

If i change the frequence with mediaclient dvbsnoop get the data from the new frequence.

I made a new observation now:
if i start sundtek-service and directly afterwards dvbtune i get a FE_STATUS. But the following calls to dvbtune are not successfull.

[log2.txt](https://github.com/sp4rkie/docsis-cable-load-monitor/files/5346319/log2.txt)

**Comment by sp4rkie** [comment] 2020-10-08 08:44
'mediasrv' must be running. 

        ps -ef|grep media


Please check. Isn't 'mediasrv'  started after reboot?

        root       301     1  5 10:39 ?        00:00:01 /opt/bin/mediasrv -d --pluginpath=/opt/bin
        root       302   301  0 10:39 ?        00:00:00 /opt/bin/mediasrv -d --pluginpath=/opt/bin


        systemctl status sundtek

should show something like this:

        ● sundtek.service - Sundtek MediaTV
           Loaded: loaded (/lib/systemd/system/sundtek.service; enabled; vendor preset: enabled)
           Active: active (exited) since Thu 2020-10-08 10:38:53 CEST; 32s ago
          Process: 198 ExecStart=/opt/bin/mediaclient --start=4 (code=exited, status=0/SUCCESS)
         Main PID: 198 (code=exited, status=0/SUCCESS)
            Tasks: 10 (limit: 2065)
           CGroup: /system.slice/sundtek.service
                   ├─301 /opt/bin/mediasrv -d --pluginpath=/opt/bin
                   └─302 /opt/bin/mediasrv -d --pluginpath=/opt/bin


does 'mediasrv' crash when used? Is something interesting logged in '/var/log/messages', '/var/log/mediasrv.log', ?

**Comment by assachs** [comment] 2020-10-08 08:48
Mediaserver is running.
`
```
pi@raspberrypi:~/cableload $ ps -ef|grep media
root     13122     1  3 09:19 ?        00:00:54 /opt/bin/mediasrv -d --pluginpath=/opt/bin
root     13123 13122  0 09:19 ?        00:00:00 /opt/bin/mediasrv -d --pluginpath=/opt/bin
pi       13244 11464  0 09:47 pts/0    00:00:00 grep --color=auto media
pi@raspberrypi:~/cableload $
```


```
 sundtek.service - Sundtek MediaTV
   Loaded: loaded (/lib/systemd/system/sundtek.service; enabled; vendor preset: enabled)
   Active: active (exited) since Thu 2020-10-08 09:19:10 BST; 26min ago
  Process: 13111 ExecStart=/opt/bin/mediaclient --start=4 (code=exited, status=0/SUCCESS)
 Main PID: 13111 (code=exited, status=0/SUCCESS)
    Tasks: 19 (limit: 4915)
   CGroup: /system.slice/sundtek.service
           ├─13121 /opt/bin/rtspd --daemon
           ├─13122 /opt/bin/mediasrv -d --pluginpath=/opt/bin
           └─13123 /opt/bin/mediasrv -d --pluginpath=/opt/bin

Oct 08 09:19:10 raspberrypi systemd[1]: Starting Sundtek MediaTV...
Oct 08 09:19:10 raspberrypi systemd[1]: Started Sundtek MediaTV.
```

```
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
Using DVB card "Sundtek DVB-C (III)"
tuning DVB-C to 698000000, srate=6952000
polling....
pi@raspberrypi:~/cableload $

```

**Comment by sp4rkie** [comment] 2020-10-08 08:51
why are these lines crossed out?

**Comment by assachs** [comment] 2020-10-08 08:55
Problem with the web form. I'm still trying to format them

**Comment by sp4rkie** [comment] 2020-10-08 09:01
> I made a new observation now:
> if i start sundtek-service and directly afterwards dvbtune i get a FE_STATUS. But the following calls to dvbtune are not successfull.

does that mean that no 'mediaclient' process is running and you must start that manually first before 'dvbtune' is working properly?

is 'mediaclient' then terminated (crashing?) after calling 'dvbtune' and you must restart that again manually before the next successful 'dvbtune' is issued?

**Comment by assachs** [comment] 2020-10-08 09:10
No, normally mediaclient is running all the time. Dvbtune is not working (always "polling".). But mediaclient is not crashing.

CableLoadMonitor tries to restart mediaclient if dvbtune is not successfull. I think i pressed ctrl-c to stop CableLoadMonitor. Then mediaclient was not running when i start to do some tests outside CableLoadMonitor.

During these tests i restarted mediaclient. Then the first call of dvbtune was successfull. But the following calls don't work.

**Comment by assachs** [comment] 2020-10-08 09:11
I tried it again. Now it is the second call:

```
pi@raspberrypi:~/cableload $ sudo systemctl restart sundtek.service;
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
Using DVB card "Sundtek DVB-C (III)"
tuning DVB-C to 698000000, srate=6952000
polling....
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
Using DVB card "Sundtek DVB-C (III)"
tuning DVB-C to 698000000, srate=6952000
polling....
Getting frontend event
FE_STATUS: FE_HAS_SIGNAL FE_HAS_LOCK FE_HAS_CARRIER FE_HAS_VITERBI FE_HAS_SYNC
Bit error rate: 0
Signal strength: 48790
SNR: 54366
FE_STATUS: FE_HAS_SIGNAL FE_HAS_LOCK FE_HAS_CARRIER FE_HAS_VITERBI FE_HAS_SYNC
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
Using DVB card "Sundtek DVB-C (III)"
tuning DVB-C to 698000000, srate=6952000
polling....
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
Using DVB card "Sundtek DVB-C (III)"
tuning DVB-C to 698000000, srate=6952000
polling....
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
Using DVB card "Sundtek DVB-C (III)"
tuning DVB-C to 698000000, srate=6952000
polling....
pi@raspberrypi:~/cableload $ sudo systemctl restart sundtek.service;
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
FD 9: fd_dvr DEMUX DEVICE: : No such file or directory
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
Using DVB card "Sundtek DVB-C (III)"
tuning DVB-C to 698000000, srate=6952000
polling....
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
Using DVB card "Sundtek DVB-C (III)"
tuning DVB-C to 698000000, srate=6952000
polling....
Getting frontend event
FE_STATUS: FE_HAS_SIGNAL FE_HAS_LOCK FE_HAS_CARRIER FE_HAS_VITERBI FE_HAS_SYNC
Bit error rate: 0
Signal strength: 54366
SNR: 54366
FE_STATUS: FE_HAS_SIGNAL FE_HAS_LOCK FE_HAS_CARRIER FE_HAS_VITERBI FE_HAS_SYNC
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
Using DVB card "Sundtek DVB-C (III)"
tuning DVB-C to 698000000, srate=6952000
polling....
pi@raspberrypi:~/cableload $ LD_PRELOAD=/opt/lib/libmediaclient.so timeout 10 dvbtune -c 0 -f 698000000 -s 6952 -qam 64
Using DVB card "Sundtek DVB-C (III)"
tuning DVB-C to 698000000, srate=6952000
polling....
```

**Comment by sp4rkie** [comment] 2020-10-08 09:28
ok, very odd. It appears to be an  issue with Sundtek firmware/hardware. What hardware and OS are you using? 

We could add an option to the script to use 'mediaclient' for tuning instead of 'dvbtune' if that works for you. This is only a workaround. A better solution:

In parallel you could open an issue here:

[Sundtek Support Forum - Index](https://support.sundtek.com/index.php)

in order to open a ticket and to explain your observations. You best make a reference to this thread then.

**Comment by assachs** [comment] 2020-10-08 09:59
debian 10.6
Linux version 5.4.51-v7l+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1333 SMP Mon Aug 10 16:51:40 BST 2020

on Raspberry 4+ 4 GB

Sundtek Firmware: newest version.

Thanks for your help 
I will open an issue at sundtek

**Comment by sp4rkie** [comment] 2020-10-08 11:59
I now tried to reproduce on Pi4 2GB and a freshly installed Pi OS. Debian + kernel as yours but with Sundtek firmware 'sundtek_installer_181220.135032.sh' (as recommended in my README). I could not reproduce the issue.

**Comment by assachs** [comment] 2020-10-08 13:02
i can confirm, that it is working with 181220.135032.

It's not working with the newest version and the first version from 2020 (i did not check all versions between).

I also checked some 2019 versions. But there are problems with the lib.

If i get an answer from sundtek i will post it here.

Thank's for your support. You responded very quickly.

**Comment by sp4rkie** [comment] 2020-10-08 13:06
I'm interested as well in what the root cause for this problem is. Thanks for reporting the issue. I hope it will make all related products better in the future :-)

Good luck.

**Comment by sp4rkie** [comment] 2020-10-08 16:10
I now tried with the most recent driver 'sundtek_installer_200507.155645.sh' as you did and can reproduce your issues :+1: 

so the best for now is to stick literally to the README and use 'sundtek_installer_181220.135032.sh' as recommended. No known problems with that version so far.

**Comment by sundtek** [comment] 2020-10-09 08:19
Hi,

thanks for reporting that issue, the signal reporting had an issue with the old DVB API. We have re-designed that interface in our driver package last year and the current version is supposed to be the better one.
The signal reporting notification was properly implemented in the new DVB API on our side and most applications (our customers are using) are probably newer applications.
And mediaclient is also more powerful than dvbtune for our devices.

thanks for reporting that issue

The driver package is already updated, this issue affected all our devices when using the old DVB API.

//Sundtek

**Comment by assachs** [comment] 2020-10-09 08:25
Hi, i can confirm that the new driver is working. Thanks.

**Comment by sp4rkie** [comment] 2020-10-09 09:08
Sundtek is known for their great product support. This issue is a further example for this. Thank you very much. So I think we happily can close this issue soon...

**Closed as completed** 2020-10-09 09:12 UTC
